### ISSUE TITLE
Issues with compiling using the IDA 7.2 SDK

### ISSUE THREAD

**Issue by BullyWiiPlaza** [decaf-emu/ida_rpl_loader#1]
I setup a project in `Visual Studio` to compile the plugin but I'm getting compilation errors from `SDK` files:

`C:\Program Files\IDA 7.2\sdk\include\idp.hpp`:

```
#ifndef __X86__
CASSERT(sizeof(processor_t) == 144);
#else
CASSERT(sizeof(processor_t) == 104);
#endif
```

`the size of an array must be greater than zero`

Same thing with `C:\Program Files\IDA 7.2\sdk\include\loader.hpp`:

```
#ifndef __X86__
  CASSERT(sizeof(plugin_t) == 64);
#else
  CASSERT(sizeof(plugin_t) == 36);
#endif
```

And in `C:\Program Files\IDA 7.2\sdk\include\netnode.hpp`:
`identifier "netlink" is undefined`

It seems like none of these are even related to the plugin but I'm wondering if you know how to fix them anyway. I doubt my `SDK` is broken but I might have forgotten to configure something correctly for the build.

**Comment by exjam** [comment]
You should follow the instructions in the sdk for building `idasdk71\install_visual.txt`, I build it in x64 Release mode:

My include directories are:
```
idasdk71\include
idasdk71\ldr
```

My preprocesser definitions are
```
__NT__
__IDP__
__X64__
```

My linked libraries are:
```
idasdk71\lib\x64_win_vc_32\ida.lib
```

**Comment by BullyWiiPlaza** [comment]
It worked. It seems like building in `Release` mode and as `x64` did the trick.
